# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a820bd8c2ca81a95e60e0090e456228be4c4a097e7a828629472f17f9ca3be2fe9226fce20aef54e4ca77b84b618c654bf27329119c16d3631050ba78bcdb3a

test:
  secret_key_base: 508cb73684443a808b7593e49ea26ea91dc069198a204e7bdf649319e127653ef10908a4d213b6823d0c7f49e338f3192033f4c0312339c604bf3ad9f24d14c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
